<?php
require_once __DIR__.'/../../private/solarex_admin_private/src/bootstrap.php';
Auth::requireLogin();
render_header('Dashboard');
if(!Database::available()){
 db_setup_notice();
 echo '<section class="grid kpis">'; render_card('Admin login','Active','Simple dev login'); render_card('Email engine','Not connected','Prepared only'); render_card('Database','Offline','Configure config.local.php'); render_card('Public site','GitHub Pages',cfg('app.public_site_url')); echo '</section>';
 render_footer(); exit;
}
function count_value(string $sql,array $params=[]): int { $r=Database::fetchOne($sql,$params); return (int)($r['c']??0); }
function status_counts(string $table,array $statuses): array { $out=[]; foreach($statuses as $s){$out[$s]=count_value("SELECT COUNT(*) AS c FROM {$table} WHERE status = :status",[':status'=>$s]);} return $out; }
function daily_counts(string $table,int $days=14): array { $rows=Database::fetchAll("SELECT DATE(created_at) AS d, COUNT(*) AS c FROM {$table} WHERE created_at >= DATE_SUB(CURDATE(), INTERVAL {$days} DAY) GROUP BY DATE(created_at) ORDER BY d ASC"); $map=[]; foreach($rows as $r){$map[(string)$r['d']]=(int)$r['c'];} $out=[]; for($i=$days-1;$i>=0;$i--){$d=date('Y-m-d',strtotime("-{$i} days")); $out[$d]=$map[$d]??0;} return $out; }
function render_bar_chart(string $title,array $data,string $note=''): void { $max=max(array_values($data)?:[1]); $max=max($max,1); echo '<section class="card chart-card"><h2>'.e($title).'</h2>'; if($note!==''){echo '<p class="muted">'.e($note).'</p>';} echo '<div class="bar-chart" role="img" aria-label="'.e($title).'">'; foreach($data as $label=>$value){$h=max(4,(int)round(((int)$value/$max)*100)); echo '<div class="bar-item"><div class="bar-track"><div class="bar-fill" style="height:'.$h.'%"></div></div><div class="bar-value">'.(int)$value.'</div><div class="bar-label">'.e((string)$label).'</div></div>'; } echo '</div></section>'; }
function render_horizontal_chart(string $title,array $data): void { $max=max(array_values($data)?:[1]); $max=max($max,1); echo '<section class="card chart-card"><h2>'.e($title).'</h2><div class="h-chart">'; foreach($data as $label=>$value){$w=max(2,(int)round(((int)$value/$max)*100)); echo '<div class="h-row"><div class="h-label">'.e((string)$label).'</div><div class="h-track"><div class="h-fill" style="width:'.$w.'%"></div></div><div class="h-value">'.(int)$value.'</div></div>'; } echo '</div></section>'; }
function render_donut_chart(string $title,int $a,int $b,string $labelA,string $labelB): void { $total=max($a+$b,1); $pct=round(($a/$total)*100,1); echo '<section class="card chart-card"><h2>'.e($title).'</h2><div class="donut-wrap"><div class="donut" style="--pct:'.e((string)$pct).'"><span>'.e((string)$pct).'%</span></div><div class="legend"><p><span class="legend-dot primary"></span>'.e($labelA).': <strong>'.(int)$a.'</strong></p><p><span class="legend-dot secondary"></span>'.e($labelB).': <strong>'.(int)$b.'</strong></p></div></div></section>'; }
$metrics=['New contacts'=>count_value("SELECT COUNT(*) AS c FROM contact_messages WHERE status = 'new'"),'Technical reviews'=>count_value("SELECT COUNT(*) AS c FROM technical_review_requests"),'ROI submissions'=>count_value("SELECT COUNT(*) AS c FROM roi_calculator_submissions"),'Downloads'=>count_value("SELECT COUNT(*) AS c FROM documentation_downloads"),'Subscribers'=>count_value("SELECT COUNT(*) AS c FROM newsletter_subscribers WHERE status = 'active'"),'Newsletter drafts'=>count_value("SELECT COUNT(*) AS c FROM newsletter_campaigns WHERE status = 'draft'"),'Email templates'=>count_value("SELECT COUNT(*) AS c FROM email_templates WHERE is_active = 1"),'Audit events'=>count_value("SELECT COUNT(*) AS c FROM admin_audit_log")];
echo '<section class="grid kpis">'; foreach($metrics as $l=>$v){render_card($l,$v);} echo '</section>';
echo '<h2>Operational control center</h2><section class="dashboard-menu-grid">';
$menu=[['Contacts','contacts.php','Contact-message inbox',$metrics['New contacts']],['Technical Reviews','technical-reviews.php','Pathway review requests',$metrics['Technical reviews']],['ROI Submissions','roi-submissions.php','Calculator lead capture',$metrics['ROI submissions']],['Documents','documents.php','Document metadata',count_value("SELECT COUNT(*) AS c FROM documents")],['Downloads','downloads.php','Download tracking',$metrics['Downloads']],['Subscribers','newsletter-subscribers.php','Newsletter audience',$metrics['Subscribers']],['Newsletters','newsletter-campaigns.php','Campaign drafts and archive',count_value("SELECT COUNT(*) AS c FROM newsletter_campaigns")],['Email Templates','email-templates.php','Thank-you and follow-up templates',$metrics['Email templates']],['Analytics','analytics.php','Charts and conversion summary','View'],['Audit Log','audit-log.php','Admin activity',$metrics['Audit events']],['Settings','settings.php','Runtime configuration',Database::available()?'OK':'Check']];
foreach($menu as [$l,$u,$d,$v]){ echo '<a class="dashboard-menu-card" href="'.e($u).'"><strong>'.e($l).'</strong><span>'.e($d).'</span><em>'.e((string)$v).'</em></a>'; } echo '</section>';
echo '<h2>Analytics overview</h2><section class="analytics-grid">'; render_bar_chart('Lead activity, last 14 days',daily_counts('contact_messages',14),'Daily contact-message volume from the database.'); render_horizontal_chart('Contact status distribution',status_counts('contact_messages',['new','in_review','replied','qualified','archived','spam'])); render_horizontal_chart('Technical review status distribution',status_counts('technical_review_requests',['new','needs_review','quartz_sio2_likely_fit','titan_tio2_likely_fit','qualified','archived'])); render_donut_chart('Email engine readiness',count_value("SELECT COUNT(*) AS c FROM email_outbox WHERE status = 'blocked_email_engine_missing'"),count_value("SELECT COUNT(*) AS c FROM email_outbox WHERE status = 'sent'"),'Prepared / blocked','Sent'); echo '</section>';
echo '<h2>Latest records</h2><section class="latest-grid"><div class="table-wrap"><h2>Latest contacts</h2><table><thead><tr><th>Date</th><th>Name</th><th>Company</th><th>Status</th><th></th></tr></thead><tbody>';
foreach(Database::fetchAll('SELECT id,name,company,email,status,created_at FROM contact_messages ORDER BY created_at DESC LIMIT 6') as $r){ echo '<tr><td data-label="Date">'.e($r['created_at']).'</td><td data-label="Name">'.e($r['name']).'<br><span class="muted">'.e($r['email']).'</span></td><td data-label="Company">'.e($r['company']).'</td><td data-label="Status">'.render_status_badge($r['status']).'</td><td data-label="Action"><a class="button secondary" href="contact-view.php?id='.(int)$r['id'].'">Open</a></td></tr>'; }
echo '</tbody></table></div><div class="table-wrap"><h2>Latest technical reviews</h2><table><thead><tr><th>Date</th><th>Company</th><th>Interest</th><th>Status</th><th></th></tr></thead><tbody>';
foreach(Database::fetchAll('SELECT id,company,product_interest,status,created_at FROM technical_review_requests ORDER BY created_at DESC LIMIT 6') as $r){ echo '<tr><td data-label="Date">'.e($r['created_at']).'</td><td data-label="Company">'.e($r['company']).'</td><td data-label="Interest">'.e($r['product_interest']).'</td><td data-label="Status">'.render_status_badge($r['status']).'</td><td data-label="Action"><a class="button secondary" href="technical-review-view.php?id='.(int)$r['id'].'">Open</a></td></tr>'; }
echo '</tbody></table></div></section>';
echo '<h2>Template readiness</h2><section class="latest-grid"><div class="table-wrap"><h2>Email templates</h2><table><thead><tr><th>Key</th><th>Name</th><th>Subject</th></tr></thead><tbody>';
foreach(Database::fetchAll('SELECT template_key,name,subject FROM email_templates ORDER BY template_key ASC LIMIT 10') as $r){ echo '<tr><td data-label="Key">'.e($r['template_key']).'</td><td data-label="Name">'.e($r['name']).'</td><td data-label="Subject">'.e($r['subject']).'</td></tr>'; }
echo '</tbody></table></div><div class="table-wrap"><h2>Newsletter campaigns</h2><table><thead><tr><th>Title</th><th>Subject</th><th>Status</th></tr></thead><tbody>';
foreach(Database::fetchAll('SELECT title,subject,status FROM newsletter_campaigns ORDER BY created_at DESC LIMIT 10') as $r){ echo '<tr><td data-label="Title">'.e($r['title']).'</td><td data-label="Subject">'.e($r['subject']).'</td><td data-label="Status">'.render_status_badge($r['status']).'</td></tr>'; }
echo '</tbody></table></div></section>';
echo '<h2>System status</h2><section class="grid kpis">';
render_card('Database','Connected','MySQL/MariaDB'); render_card('Email engine', cfg('email_engine.enabled') ? 'Connected' : 'Not connected', cfg('email_engine.provider','not_connected')); render_card('Admin URL', 'solarex_admin', cfg('app.admin_base_url')); render_card('Forms URL', 'solarex_forms', cfg('app.forms_base_url')); echo '</section>';
render_footer();
